
services:
  backend:
    build: ./backend
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=${DB_USER}
      - DATABASE_NAME=${DB_NAME}
      - DATABASE_PASSWORD=${DB_PASSWORD}
    ports: #expose outside for debugging
      - "3000:3000"
    depends_on:
      - db
    networks:
      - matcha
    volumes:
      - ./backend/src:/usr/src/app/src
    restart: unless-stopped

  frontend:
    build: ./frontend
    environment:
      - PORT=${FRONTEND_PORT}
      - REACT_APP_BACKEND_URL=${BACKEND_URL}
    ports:
      - "4000:4000"
    depends_on:
      - backend
    networks:
      - matcha
    volumes:
      - ./frontend/src:/usr/src/app/src
    restart: unless-stopped

  db:
    build: ./db
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    expose:
        - "3306"
    networks:
      - matcha
    volumes:
      - ./db/data:/var/lib/mysql
    restart: unless-stopped

networks:
  matcha:
    name: matcha
    driver: bridge
