
services:
  backend:
    build: ./backend
    container_name: matcha-backend
    environment:
      - DATABASE_NAME=${DB_NAME}
      - DATABASE_USER=${DB_USER}
      - DATABASE_PASSWORD=${DB_PASSWORD}
      - DATABASE_HOST=${DB_HOST}
      - DATABASE_PORT=${DB_PORT}
    ports: #expose outside for debugging
      - "3000:3000"
    depends_on:
      - db
    networks:
      - matcha-networks
    volumes:
      - ./backend/src:/usr/src/app/src
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: matcha-frontend
    environment:
      - PORT=${FRONTEND_PORT}
      - REACT_APP_BACKEND_URL=${BACKEND_URL}
    ports:
      - "4000:4000"
    depends_on:
      - backend
    networks:
      - matcha-networks
    volumes:
      - ./frontend/src:/usr/src/app/src
    restart: unless-stopped

  db:
    build: ./db
    container_name: matcha-db
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_PORT=${DB_PORT}
    expose:
        - "3306"
    networks:
      - matcha-networks
    volumes:
      - ./db/data:/var/lib/mysql
    restart: unless-stopped

networks:
  matcha-networks:
    driver: bridge

volumes:
  db-data: